phpbbmodders_contactadmin_displayform:
    path: /contactadmin
    defaults: { _controller: phpbbmodders.contactadmin.main.controller:displayform }

phpbbmodders_contactadmin_botuserinfo:
    path: /contact_bot_info/{user_id}
    defaults: { _controller: phpbbmodders.contactadmin.core:bot_user_info }
    requirements:
        user_id: \d+